- hosts: all
  become: yes

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name:
          - apache2
          - apache2-dev
        state: present

    - name: Copy configuration files
      copy:
        src: httpd.conf
        dest: /etc/apache2/apache2.conf

    - name: Copy virtual hosts configuration file
      copy:
        src: httpd-vhosts.conf
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Start Apache and configure it to run at boot
      service:
        name: apache2
        state: started
        enabled: yes